import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import Pokemon from "../components/Pokemon";
import { IPokemon } from "../interfaces";
import styles from "../styles/Home.module.css";

interface HomeProps {
  pokemon: IPokemon[];
}

const Home: NextPage<HomeProps> = ({ pokemon }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>POKEDEX</h1>

      <div className={styles.grid}>
        {pokemon.map((item) => (
          <Pokemon key={item.id} pokemon={item} />
        ))}
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const response = await fetch(
    "https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json"
  );

  const data: IPokemon[] = await response.json();

  return {
    props: {
      pokemon: data,
    },
  };
};
